; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes='loop-mssa(licm)' < %s | FileCheck %s

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"

; A loop-invariant masked load/store pair is promoted to a value carried across
; the loop: one masked load in the preheader, one masked store in the exit.

define void @promote_full_mask(ptr noalias %acc, ptr noalias %src, i64 %n) {
; CHECK-LABEL: define void @promote_full_mask(
; CHECK-SAME: ptr noalias [[ACC:%.*]], ptr noalias [[SRC:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[ACC_PROMOTED:%.*]] = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 [[ACC]], <4 x i1> splat (i1 true), <4 x double> poison)
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[ADD1:%.*]] = phi <4 x double> [ [[ACC_PROMOTED]], %[[ENTRY]] ], [ [[ADD:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr double, ptr [[SRC]], i64 [[I]]
; CHECK-NEXT:    [[X:%.*]] = load <4 x double>, ptr [[GEP]], align 32
; CHECK-NEXT:    [[ADD]] = fadd <4 x double> [[ADD1]], [[X]]
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[ADD_LCSSA:%.*]] = phi <4 x double> [ [[ADD]], %[[LOOP]] ]
; CHECK-NEXT:    call void @llvm.masked.store.v4f64.p0(<4 x double> [[ADD_LCSSA]], ptr align 32 [[ACC]], <4 x i1> splat (i1 true))
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %v = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 %acc, <4 x i1> splat (i1 true), <4 x double> poison)
  %gep = getelementptr double, ptr %src, i64 %i
  %x = load <4 x double>, ptr %gep, align 32
  %add = fadd <4 x double> %v, %x
  call void @llvm.masked.store.v4f64.p0(<4 x double> %add, ptr align 32 %acc, <4 x i1> splat (i1 true))
  %i.next = add i64 %i, 4
  %cmp = icmp ult i64 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Same, with a partially enabled constant mask: the promoted load and store
; keep that mask, so only the enabled lanes are ever touched.

define void @promote_partial_mask(ptr noalias %acc, ptr noalias %src, i64 %n) {
; CHECK-LABEL: define void @promote_partial_mask(
; CHECK-SAME: ptr noalias [[ACC:%.*]], ptr noalias [[SRC:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[ACC_PROMOTED:%.*]] = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 [[ACC]], <4 x i1> <i1 true, i1 true, i1 true, i1 false>, <4 x double> poison)
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[ADD1:%.*]] = phi <4 x double> [ [[ACC_PROMOTED]], %[[ENTRY]] ], [ [[ADD:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr double, ptr [[SRC]], i64 [[I]]
; CHECK-NEXT:    [[X:%.*]] = load <4 x double>, ptr [[GEP]], align 32
; CHECK-NEXT:    [[ADD]] = fadd <4 x double> [[ADD1]], [[X]]
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[ADD_LCSSA:%.*]] = phi <4 x double> [ [[ADD]], %[[LOOP]] ]
; CHECK-NEXT:    call void @llvm.masked.store.v4f64.p0(<4 x double> [[ADD_LCSSA]], ptr align 32 [[ACC]], <4 x i1> <i1 true, i1 true, i1 true, i1 false>)
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %v = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 %acc, <4 x i1> <i1 true, i1 true, i1 true, i1 false>, <4 x double> poison)
  %gep = getelementptr double, ptr %src, i64 %i
  %x = load <4 x double>, ptr %gep, align 32
  %add = fadd <4 x double> %v, %x
  call void @llvm.masked.store.v4f64.p0(<4 x double> %add, ptr align 32 %acc, <4 x i1> <i1 true, i1 true, i1 true, i1 false>)
  %i.next = add i64 %i, 4
  %cmp = icmp ult i64 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; The extent of a masked access is measured from its enabled lanes, not from
; its vector type. Here the accumulator is the 3-lane prefix of a
; <4 x double> row, so it covers 24 bytes, and the next row of the tile starts
; exactly 24 bytes further on. Modelling the access with its full 32-byte type
; would make the two rows look like they overlap and would block promotion.

define void @promote_tile_row_vs_plain_store(ptr noalias %tile, ptr noalias %src, i64 %n) {
; CHECK-LABEL: define void @promote_tile_row_vs_plain_store(
; CHECK-SAME: ptr noalias [[TILE:%.*]], ptr noalias [[SRC:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[ROW1:%.*]] = getelementptr inbounds double, ptr [[TILE]], i64 3
; CHECK-NEXT:    [[TILE_PROMOTED:%.*]] = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 [[TILE]], <4 x i1> <i1 true, i1 true, i1 true, i1 false>, <4 x double> poison)
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[ADD1:%.*]] = phi <4 x double> [ [[TILE_PROMOTED]], %[[ENTRY]] ], [ [[ADD:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr double, ptr [[SRC]], i64 [[I]]
; CHECK-NEXT:    [[X:%.*]] = load <2 x double>, ptr [[GEP]], align 16
; CHECK-NEXT:    [[XW:%.*]] = shufflevector <2 x double> [[X]], <2 x double> poison, <4 x i32> <i32 0, i32 1, i32 0, i32 1>
; CHECK-NEXT:    [[ADD]] = fadd <4 x double> [[ADD1]], [[XW]]
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[X_LCSSA:%.*]] = phi <2 x double> [ [[X]], %[[LOOP]] ]
; CHECK-NEXT:    [[ADD_LCSSA:%.*]] = phi <4 x double> [ [[ADD]], %[[LOOP]] ]
; CHECK-NEXT:    call void @llvm.masked.store.v4f64.p0(<4 x double> [[ADD_LCSSA]], ptr align 32 [[TILE]], <4 x i1> <i1 true, i1 true, i1 true, i1 false>)
; CHECK-NEXT:    store <2 x double> [[X_LCSSA]], ptr [[ROW1]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %row1 = getelementptr inbounds double, ptr %tile, i64 3
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %v = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 %tile, <4 x i1> <i1 true, i1 true, i1 true, i1 false>, <4 x double> poison)
  %gep = getelementptr double, ptr %src, i64 %i
  %x = load <2 x double>, ptr %gep, align 16
  %xw = shufflevector <2 x double> %x, <2 x double> poison, <4 x i32> <i32 0, i32 1, i32 0, i32 1>
  %add = fadd <4 x double> %v, %xw
  call void @llvm.masked.store.v4f64.p0(<4 x double> %add, ptr align 32 %tile, <4 x i1> <i1 true, i1 true, i1 true, i1 false>)
  store <2 x double> %x, ptr %row1, align 8
  %i.next = add i64 %i, 4
  %cmp = icmp ult i64 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Same disjointness question, but the neighbouring access is itself a masked
; intrinsic, and it comes first in memory. Alias analysis has no size for the
; pointer argument of such a call, so it cannot rule out that the neighbour
; reaches forward into the promoted row; comparing the two enabled extents
; against their common base does.

define <4 x double> @promote_tile_row_vs_masked_load(ptr noalias %tile, i64 %n) {
; CHECK-LABEL: define <4 x double> @promote_tile_row_vs_masked_load(
; CHECK-SAME: ptr noalias [[TILE:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[ROW1:%.*]] = getelementptr inbounds double, ptr [[TILE]], i64 3
; CHECK-NEXT:    [[N0:%.*]] = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 [[TILE]], <4 x i1> <i1 true, i1 true, i1 true, i1 false>, <4 x double> poison)
; CHECK-NEXT:    [[ROW1_PROMOTED:%.*]] = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 8 [[ROW1]], <4 x i1> <i1 true, i1 true, i1 true, i1 false>, <4 x double> poison)
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[ADD1:%.*]] = phi <4 x double> [ [[ROW1_PROMOTED]], %[[ENTRY]] ], [ [[ADD:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ACC_PHI:%.*]] = phi <4 x double> [ zeroinitializer, %[[ENTRY]] ], [ [[NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ADD]] = fadd <4 x double> [[ADD1]], splat (double 1.000000e+00)
; CHECK-NEXT:    [[NEXT]] = fadd <4 x double> [[ACC_PHI]], [[N0]]
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[ADD_LCSSA:%.*]] = phi <4 x double> [ [[ADD]], %[[LOOP]] ]
; CHECK-NEXT:    [[NEXT_LCSSA:%.*]] = phi <4 x double> [ [[NEXT]], %[[LOOP]] ]
; CHECK-NEXT:    call void @llvm.masked.store.v4f64.p0(<4 x double> [[ADD_LCSSA]], ptr align 8 [[ROW1]], <4 x i1> <i1 true, i1 true, i1 true, i1 false>)
; CHECK-NEXT:    ret <4 x double> [[NEXT_LCSSA]]
;
entry:
  %row1 = getelementptr inbounds double, ptr %tile, i64 3
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %acc.phi = phi <4 x double> [ zeroinitializer, %entry ], [ %next, %loop ]
  %v = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 8 %row1, <4 x i1> <i1 true, i1 true, i1 true, i1 false>, <4 x double> poison)
  %add = fadd <4 x double> %v, splat (double 1.000000e+00)
  call void @llvm.masked.store.v4f64.p0(<4 x double> %add, ptr align 8 %row1, <4 x i1> <i1 true, i1 true, i1 true, i1 false>)
  %n0 = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 %tile, <4 x i1> <i1 true, i1 true, i1 true, i1 false>, <4 x double> poison)
  %next = fadd <4 x double> %acc.phi, %n0
  %i.next = add i64 %i, 4
  %cmp = icmp ult i64 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret <4 x double> %next
}

; Within a block the accesses are ordered: the second load reads the value the
; first store wrote, so it becomes that value rather than a live-in.

define void @promote_two_pairs_in_one_block(ptr noalias %acc, ptr noalias %src, i64 %n) {
; CHECK-LABEL: define void @promote_two_pairs_in_one_block(
; CHECK-SAME: ptr noalias [[ACC:%.*]], ptr noalias [[SRC:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[ACC_PROMOTED:%.*]] = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 [[ACC]], <4 x i1> splat (i1 true), <4 x double> poison)
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[ADD11:%.*]] = phi <4 x double> [ [[ACC_PROMOTED]], %[[ENTRY]] ], [ [[ADD1:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr double, ptr [[SRC]], i64 [[I]]
; CHECK-NEXT:    [[X:%.*]] = load <4 x double>, ptr [[GEP]], align 32
; CHECK-NEXT:    [[ADD0:%.*]] = fadd <4 x double> [[ADD11]], [[X]]
; CHECK-NEXT:    [[ADD1]] = fmul <4 x double> [[ADD0]], [[X]]
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[ADD1_LCSSA:%.*]] = phi <4 x double> [ [[ADD1]], %[[LOOP]] ]
; CHECK-NEXT:    call void @llvm.masked.store.v4f64.p0(<4 x double> [[ADD1_LCSSA]], ptr align 32 [[ACC]], <4 x i1> splat (i1 true))
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %v0 = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 %acc, <4 x i1> splat (i1 true), <4 x double> poison)
  %gep = getelementptr double, ptr %src, i64 %i
  %x = load <4 x double>, ptr %gep, align 32
  %add0 = fadd <4 x double> %v0, %x
  call void @llvm.masked.store.v4f64.p0(<4 x double> %add0, ptr align 32 %acc, <4 x i1> splat (i1 true))
  %v1 = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 %acc, <4 x i1> splat (i1 true), <4 x double> poison)
  %add1 = fmul <4 x double> %v1, %x
  call void @llvm.masked.store.v4f64.p0(<4 x double> %add1, ptr align 32 %acc, <4 x i1> splat (i1 true))
  %i.next = add i64 %i, 4
  %cmp = icmp ult i64 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; With several exits, the live-out value is stored on each of them.

define void @promote_multiple_exits(ptr noalias %acc, ptr noalias %src, i64 %n) {
; CHECK-LABEL: define void @promote_multiple_exits(
; CHECK-SAME: ptr noalias [[ACC:%.*]], ptr noalias [[SRC:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[EARLY:%.*]] = fcmp ogt double 0.000000e+00, 1.000000e+00
; CHECK-NEXT:    [[ACC_PROMOTED:%.*]] = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 [[ACC]], <4 x i1> splat (i1 true), <4 x double> poison)
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[ADD1:%.*]] = phi <4 x double> [ [[ACC_PROMOTED]], %[[ENTRY]] ], [ [[ADD:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LATCH]] ]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr double, ptr [[SRC]], i64 [[I]]
; CHECK-NEXT:    [[X:%.*]] = load <4 x double>, ptr [[GEP]], align 32
; CHECK-NEXT:    [[ADD]] = fadd <4 x double> [[ADD1]], [[X]]
; CHECK-NEXT:    br i1 [[EARLY]], label %[[EXIT_EARLY:.*]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT_EARLY]]:
; CHECK-NEXT:    [[ADD_LCSSA:%.*]] = phi <4 x double> [ [[ADD]], %[[LOOP]] ]
; CHECK-NEXT:    call void @llvm.masked.store.v4f64.p0(<4 x double> [[ADD_LCSSA]], ptr align 32 [[ACC]], <4 x i1> splat (i1 true))
; CHECK-NEXT:    ret void
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[ADD_LCSSA2:%.*]] = phi <4 x double> [ [[ADD]], %[[LATCH]] ]
; CHECK-NEXT:    call void @llvm.masked.store.v4f64.p0(<4 x double> [[ADD_LCSSA2]], ptr align 32 [[ACC]], <4 x i1> splat (i1 true))
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %latch ]
  %v = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 %acc, <4 x i1> splat (i1 true), <4 x double> poison)
  %gep = getelementptr double, ptr %src, i64 %i
  %x = load <4 x double>, ptr %gep, align 32
  %add = fadd <4 x double> %v, %x
  call void @llvm.masked.store.v4f64.p0(<4 x double> %add, ptr align 32 %acc, <4 x i1> splat (i1 true))
  %early = fcmp ogt double 0.000000e+00, 1.000000e+00
  br i1 %early, label %exit.early, label %latch

latch:
  %i.next = add i64 %i, 4
  %cmp = icmp ult i64 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit.early:
  ret void

exit:
  ret void
}

; Two independent groups in the same loop are promoted independently.

define void @promote_two_groups(ptr noalias %a, ptr noalias %b, ptr noalias %src, i64 %n) {
; CHECK-LABEL: define void @promote_two_groups(
; CHECK-SAME: ptr noalias [[A:%.*]], ptr noalias [[B:%.*]], ptr noalias [[SRC:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[A_PROMOTED:%.*]] = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 [[A]], <4 x i1> splat (i1 true), <4 x double> poison)
; CHECK-NEXT:    [[B_PROMOTED:%.*]] = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 [[B]], <4 x i1> splat (i1 true), <4 x double> poison)
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[ADDB2:%.*]] = phi <4 x double> [ [[B_PROMOTED]], %[[ENTRY]] ], [ [[ADDB:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ADDA1:%.*]] = phi <4 x double> [ [[A_PROMOTED]], %[[ENTRY]] ], [ [[ADDA:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr double, ptr [[SRC]], i64 [[I]]
; CHECK-NEXT:    [[X:%.*]] = load <4 x double>, ptr [[GEP]], align 32
; CHECK-NEXT:    [[ADDA]] = fadd <4 x double> [[ADDA1]], [[X]]
; CHECK-NEXT:    [[ADDB]] = fmul <4 x double> [[ADDB2]], [[X]]
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[ADDB_LCSSA:%.*]] = phi <4 x double> [ [[ADDB]], %[[LOOP]] ]
; CHECK-NEXT:    [[ADDA_LCSSA:%.*]] = phi <4 x double> [ [[ADDA]], %[[LOOP]] ]
; CHECK-NEXT:    call void @llvm.masked.store.v4f64.p0(<4 x double> [[ADDA_LCSSA]], ptr align 32 [[A]], <4 x i1> splat (i1 true))
; CHECK-NEXT:    call void @llvm.masked.store.v4f64.p0(<4 x double> [[ADDB_LCSSA]], ptr align 32 [[B]], <4 x i1> splat (i1 true))
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %gep = getelementptr double, ptr %src, i64 %i
  %x = load <4 x double>, ptr %gep, align 32
  %va = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 %a, <4 x i1> splat (i1 true), <4 x double> poison)
  %adda = fadd <4 x double> %va, %x
  call void @llvm.masked.store.v4f64.p0(<4 x double> %adda, ptr align 32 %a, <4 x i1> splat (i1 true))
  %vb = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 %b, <4 x i1> splat (i1 true), <4 x double> poison)
  %addb = fmul <4 x double> %vb, %x
  call void @llvm.masked.store.v4f64.p0(<4 x double> %addb, ptr align 32 %b, <4 x i1> splat (i1 true))
  %i.next = add i64 %i, 4
  %cmp = icmp ult i64 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; A set with no store is not a promotion candidate: the alias set carries no
; Mod, and there is no value to carry across the loop.

define <4 x double> @no_store_in_group(ptr noalias %acc, i64 %n) {
; CHECK-LABEL: define <4 x double> @no_store_in_group(
; CHECK-SAME: ptr noalias [[ACC:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[V:%.*]] = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 [[ACC]], <4 x i1> splat (i1 true), <4 x double> poison)
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ACC_PHI:%.*]] = phi <4 x double> [ zeroinitializer, %[[ENTRY]] ], [ [[ADD:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ADD]] = fadd <4 x double> [[ACC_PHI]], [[V]]
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[ADD_LCSSA:%.*]] = phi <4 x double> [ [[ADD]], %[[LOOP]] ]
; CHECK-NEXT:    ret <4 x double> [[ADD_LCSSA]]
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %acc.phi = phi <4 x double> [ zeroinitializer, %entry ], [ %add, %loop ]
  %v = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 %acc, <4 x i1> splat (i1 true), <4 x double> poison)
  %add = fadd <4 x double> %acc.phi, %v
  %i.next = add i64 %i, 4
  %cmp = icmp ult i64 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret <4 x double> %add
}

; Negative: a varying pointer is not a group at all.

define void @variant_pointer(ptr noalias %acc, ptr noalias %src, i64 %n) {
; CHECK-LABEL: define void @variant_pointer(
; CHECK-SAME: ptr noalias [[ACC:%.*]], ptr noalias [[SRC:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[PTR:%.*]] = getelementptr double, ptr [[ACC]], i64 [[I]]
; CHECK-NEXT:    [[V:%.*]] = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 [[PTR]], <4 x i1> splat (i1 true), <4 x double> poison)
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr double, ptr [[SRC]], i64 [[I]]
; CHECK-NEXT:    [[X:%.*]] = load <4 x double>, ptr [[GEP]], align 32
; CHECK-NEXT:    [[ADD:%.*]] = fadd <4 x double> [[V]], [[X]]
; CHECK-NEXT:    call void @llvm.masked.store.v4f64.p0(<4 x double> [[ADD]], ptr align 32 [[PTR]], <4 x i1> splat (i1 true))
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %ptr = getelementptr double, ptr %acc, i64 %i
  %v = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 %ptr, <4 x i1> splat (i1 true), <4 x double> poison)
  %gep = getelementptr double, ptr %src, i64 %i
  %x = load <4 x double>, ptr %gep, align 32
  %add = fadd <4 x double> %v, %x
  call void @llvm.masked.store.v4f64.p0(<4 x double> %add, ptr align 32 %ptr, <4 x i1> splat (i1 true))
  %i.next = add i64 %i, 4
  %cmp = icmp ult i64 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Negative: a varying mask means the set of live lanes changes per iteration,
; so no single load/store pair can stand in for the loop's accesses.

define void @variant_mask(ptr noalias %acc, ptr noalias %src, i64 %n) {
; CHECK-LABEL: define void @variant_mask(
; CHECK-SAME: ptr noalias [[ACC:%.*]], ptr noalias [[SRC:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IV:%.*]] = insertelement <4 x i64> poison, i64 [[I]], i32 0
; CHECK-NEXT:    [[SP:%.*]] = shufflevector <4 x i64> [[IV]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[MASK:%.*]] = icmp ult <4 x i64> [[SP]], splat (i64 3)
; CHECK-NEXT:    [[V:%.*]] = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 [[ACC]], <4 x i1> [[MASK]], <4 x double> poison)
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr double, ptr [[SRC]], i64 [[I]]
; CHECK-NEXT:    [[X:%.*]] = load <4 x double>, ptr [[GEP]], align 32
; CHECK-NEXT:    [[ADD:%.*]] = fadd <4 x double> [[V]], [[X]]
; CHECK-NEXT:    call void @llvm.masked.store.v4f64.p0(<4 x double> [[ADD]], ptr align 32 [[ACC]], <4 x i1> [[MASK]])
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %iv = insertelement <4 x i64> poison, i64 %i, i32 0
  %sp = shufflevector <4 x i64> %iv, <4 x i64> poison, <4 x i32> zeroinitializer
  %mask = icmp ult <4 x i64> %sp, splat (i64 3)
  %v = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 %acc, <4 x i1> %mask, <4 x double> poison)
  %gep = getelementptr double, ptr %src, i64 %i
  %x = load <4 x double>, ptr %gep, align 32
  %add = fadd <4 x double> %v, %x
  call void @llvm.masked.store.v4f64.p0(<4 x double> %add, ptr align 32 %acc, <4 x i1> %mask)
  %i.next = add i64 %i, 4
  %cmp = icmp ult i64 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Negative: another access in the loop may touch the same location, so a value
; carried in a register would go stale.

define void @aliasing_access_in_loop(ptr %acc, ptr %other, i64 %n) {
; CHECK-LABEL: define void @aliasing_access_in_loop(
; CHECK-SAME: ptr [[ACC:%.*]], ptr [[OTHER:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[V:%.*]] = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 [[ACC]], <4 x i1> splat (i1 true), <4 x double> poison)
; CHECK-NEXT:    [[ADD:%.*]] = fadd <4 x double> [[V]], splat (double 1.000000e+00)
; CHECK-NEXT:    call void @llvm.masked.store.v4f64.p0(<4 x double> [[ADD]], ptr align 32 [[ACC]], <4 x i1> splat (i1 true))
; CHECK-NEXT:    store <4 x double> zeroinitializer, ptr [[OTHER]], align 32
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %v = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 %acc, <4 x i1> splat (i1 true), <4 x double> poison)
  %add = fadd <4 x double> %v, splat (double 1.000000e+00)
  call void @llvm.masked.store.v4f64.p0(<4 x double> %add, ptr align 32 %acc, <4 x i1> splat (i1 true))
  store <4 x double> zeroinitializer, ptr %other, align 32
  %i.next = add i64 %i, 4
  %cmp = icmp ult i64 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Negative: an unknown call in the loop may read or write the location.

define void @opaque_call_in_loop(ptr noalias %acc, i64 %n) {
; CHECK-LABEL: define void @opaque_call_in_loop(
; CHECK-SAME: ptr noalias [[ACC:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[V:%.*]] = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 [[ACC]], <4 x i1> splat (i1 true), <4 x double> poison)
; CHECK-NEXT:    [[ADD:%.*]] = fadd <4 x double> [[V]], splat (double 1.000000e+00)
; CHECK-NEXT:    call void @llvm.masked.store.v4f64.p0(<4 x double> [[ADD]], ptr align 32 [[ACC]], <4 x i1> splat (i1 true))
; CHECK-NEXT:    call void @use(ptr [[ACC]])
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %v = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 %acc, <4 x i1> splat (i1 true), <4 x double> poison)
  %add = fadd <4 x double> %v, splat (double 1.000000e+00)
  call void @llvm.masked.store.v4f64.p0(<4 x double> %add, ptr align 32 %acc, <4 x i1> splat (i1 true))
  call void @use(ptr %acc)
  %i.next = add i64 %i, 4
  %cmp = icmp ult i64 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; The store is conditional, so it does not dominate the exit and cannot be
; sunk. The load still executes on every iteration, so it is hoisted on its
; own and the store stays in the loop -- LICM's load-only promotion.

define void @store_does_not_dominate_exit(ptr noalias %acc, ptr noalias %src, i64 %n, i1 %c) {
; CHECK-LABEL: define void @store_does_not_dominate_exit(
; CHECK-SAME: ptr noalias [[ACC:%.*]], ptr noalias [[SRC:%.*]], i64 [[N:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[ACC_PROMOTED:%.*]] = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 [[ACC]], <4 x i1> splat (i1 true), <4 x double> poison)
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[ADD2:%.*]] = phi <4 x double> [ [[ACC_PROMOTED]], %[[ENTRY]] ], [ [[ADD1:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LATCH]] ]
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[LATCH]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr double, ptr [[SRC]], i64 [[I]]
; CHECK-NEXT:    [[X:%.*]] = load <4 x double>, ptr [[GEP]], align 32
; CHECK-NEXT:    [[ADD:%.*]] = fadd <4 x double> [[ADD2]], [[X]]
; CHECK-NEXT:    call void @llvm.masked.store.v4f64.p0(<4 x double> [[ADD]], ptr align 32 [[ACC]], <4 x i1> splat (i1 true))
; CHECK-NEXT:    br label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[ADD1]] = phi <4 x double> [ [[ADD]], %[[THEN]] ], [ [[ADD2]], %[[LOOP]] ]
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %latch ]
  %v = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 %acc, <4 x i1> splat (i1 true), <4 x double> poison)
  br i1 %c, label %then, label %latch

then:
  %gep = getelementptr double, ptr %src, i64 %i
  %x = load <4 x double>, ptr %gep, align 32
  %add = fadd <4 x double> %v, %x
  call void @llvm.masked.store.v4f64.p0(<4 x double> %add, ptr align 32 %acc, <4 x i1> splat (i1 true))
  br label %latch

latch:
  %i.next = add i64 %i, 4
  %cmp = icmp ult i64 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; A scalable access has no statically known extent, but alias analysis models
; that directly, so promotion needs nothing special for it.

define void @scalable_access(ptr noalias %acc, ptr noalias %src, i64 %n) {
; CHECK-LABEL: define void @scalable_access(
; CHECK-SAME: ptr noalias [[ACC:%.*]], ptr noalias [[SRC:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[ACC_PROMOTED:%.*]] = call <vscale x 4 x double> @llvm.masked.load.nxv4f64.p0(ptr align 32 [[ACC]], <vscale x 4 x i1> splat (i1 true), <vscale x 4 x double> poison)
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[ADD1:%.*]] = phi <vscale x 4 x double> [ [[ACC_PROMOTED]], %[[ENTRY]] ], [ [[ADD:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr double, ptr [[SRC]], i64 [[I]]
; CHECK-NEXT:    [[X:%.*]] = load <vscale x 4 x double>, ptr [[GEP]], align 32
; CHECK-NEXT:    [[ADD]] = fadd <vscale x 4 x double> [[ADD1]], [[X]]
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[ADD_LCSSA:%.*]] = phi <vscale x 4 x double> [ [[ADD]], %[[LOOP]] ]
; CHECK-NEXT:    call void @llvm.masked.store.nxv4f64.p0(<vscale x 4 x double> [[ADD_LCSSA]], ptr align 32 [[ACC]], <vscale x 4 x i1> splat (i1 true))
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %v = call <vscale x 4 x double> @llvm.masked.load.nxv4f64.p0(ptr align 32 %acc, <vscale x 4 x i1> splat (i1 true), <vscale x 4 x double> poison)
  %gep = getelementptr double, ptr %src, i64 %i
  %x = load <vscale x 4 x double>, ptr %gep, align 32
  %add = fadd <vscale x 4 x double> %v, %x
  call void @llvm.masked.store.nxv4f64.p0(<vscale x 4 x double> %add, ptr align 32 %acc, <vscale x 4 x i1> splat (i1 true))
  %i.next = add i64 %i, 4
  %cmp = icmp ult i64 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Negative: the two members of the group access different types, so no single
; promoted value can stand in for both.

define void @mismatched_access_types(ptr noalias %acc, i64 %n) {
; CHECK-LABEL: define void @mismatched_access_types(
; CHECK-SAME: ptr noalias [[ACC:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[V:%.*]] = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 [[ACC]], <4 x i1> splat (i1 true), <4 x double> poison)
; CHECK-NEXT:    [[ADD:%.*]] = fadd <4 x double> [[V]], splat (double 1.000000e+00)
; CHECK-NEXT:    [[TRUNC:%.*]] = fptrunc <4 x double> [[ADD]] to <4 x float>
; CHECK-NEXT:    call void @llvm.masked.store.v4f32.p0(<4 x float> [[TRUNC]], ptr align 32 [[ACC]], <4 x i1> splat (i1 true))
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %v = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 %acc, <4 x i1> splat (i1 true), <4 x double> poison)
  %add = fadd <4 x double> %v, splat (double 1.000000e+00)
  %trunc = fptrunc <4 x double> %add to <4 x float>
  call void @llvm.masked.store.v4f32.p0(<4 x float> %trunc, ptr align 32 %acc, <4 x i1> splat (i1 true))
  %i.next = add i64 %i, 4
  %cmp = icmp ult i64 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Negative: two different invariant masks on the same pointer. One promoted
; value cannot stand in for accesses covering different lanes.

define void @two_masks(ptr noalias %p, i64 %n) {
; CHECK-LABEL: define void @two_masks(
; CHECK-SAME: ptr noalias [[P:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[V:%.*]] = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 [[P]], <4 x i1> <i1 true, i1 true, i1 false, i1 false>, <4 x double> poison)
; CHECK-NEXT:    [[A:%.*]] = fadd <4 x double> [[V]], splat (double 1.000000e+00)
; CHECK-NEXT:    call void @llvm.masked.store.v4f64.p0(<4 x double> [[A]], ptr align 32 [[P]], <4 x i1> <i1 true, i1 true, i1 true, i1 false>)
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %v = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 32 %p, <4 x i1> <i1 true, i1 true, i1 false, i1 false>, <4 x double> poison)
  %a = fadd <4 x double> %v, splat (double 1.000000e+00)
  call void @llvm.masked.store.v4f64.p0(<4 x double> %a, ptr align 32 %p, <4 x i1> <i1 true, i1 true, i1 true, i1 false>)
  %i.next = add i64 %i, 4
  %cmp = icmp ult i64 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

; Negative: a plain access and a masked one on the same location. The plain
; load reads lanes the promoted value would not cover.

define void @mixed_plain_and_masked(ptr noalias %p, i64 %n) {
; CHECK-LABEL: define void @mixed_plain_and_masked(
; CHECK-SAME: ptr noalias [[P:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[V:%.*]] = load <4 x double>, ptr [[P]], align 32
; CHECK-NEXT:    [[A:%.*]] = fadd <4 x double> [[V]], splat (double 1.000000e+00)
; CHECK-NEXT:    call void @llvm.masked.store.v4f64.p0(<4 x double> [[A]], ptr align 32 [[P]], <4 x i1> <i1 true, i1 true, i1 true, i1 false>)
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %v = load <4 x double>, ptr %p, align 32
  %a = fadd <4 x double> %v, splat (double 1.000000e+00)
  call void @llvm.masked.store.v4f64.p0(<4 x double> %a, ptr align 32 %p, <4 x i1> <i1 true, i1 true, i1 true, i1 false>)
  %i.next = add i64 %i, 4
  %cmp = icmp ult i64 %i.next, %n
  br i1 %cmp, label %loop, label %exit

exit:
  ret void
}

declare void @use(ptr)
