; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -aa-pipeline=basic-aa -passes=dse -S | FileCheck %s

; A masked memory operation whose constant mask enables a prefix of the vector
; touches only those lanes, so its footprint is smaller than its vector type.

; The masked store writes tile[0, 24); the only read is at tile+24, so nothing
; reads it and it is dead. Sized by its <4 x double> type it would appear to
; write tile[0, 32) and overlap the read.
define <4 x double> @dead_store_under_prefix_mask(ptr %p) {
; CHECK-LABEL: define <4 x double> @dead_store_under_prefix_mask(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    [[TILE:%.*]] = alloca [16 x double], align 32
; CHECK-NEXT:    [[ROW1:%.*]] = getelementptr inbounds nuw i8, ptr [[TILE]], i64 24
; CHECK-NEXT:    [[V:%.*]] = load <4 x double>, ptr [[P]], align 32
; CHECK-NEXT:    call void @llvm.masked.store.v4f64.p0(<4 x double> [[V]], ptr align 8 [[ROW1]], <4 x i1> <i1 true, i1 true, i1 true, i1 false>)
; CHECK-NEXT:    [[R:%.*]] = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 8 [[ROW1]], <4 x i1> <i1 true, i1 true, i1 true, i1 false>, <4 x double> poison)
; CHECK-NEXT:    ret <4 x double> [[R]]
;
  %tile = alloca [16 x double], align 32
  %row1 = getelementptr inbounds nuw i8, ptr %tile, i64 24
  %v = load <4 x double>, ptr %p, align 32
  call void @llvm.masked.store.v4f64.p0(<4 x double> %v, ptr align 8 %tile, <4 x i1> <i1 true, i1 true, i1 true, i1 false>)
  call void @llvm.masked.store.v4f64.p0(<4 x double> %v, ptr align 8 %row1, <4 x i1> <i1 true, i1 true, i1 true, i1 false>)
  %r = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 8 %row1, <4 x i1> <i1 true, i1 true, i1 true, i1 false>, <4 x double> poison)
  ret <4 x double> %r
}

; The footprint must be exact, not an upper bound: proving the plain 24-byte
; store completely overwrites the masked one is what kills it.
define void @masked_store_fully_overwritten(ptr %q, ptr %p) {
; CHECK-LABEL: define void @masked_store_fully_overwritten(
; CHECK-SAME: ptr [[Q:%.*]], ptr [[P:%.*]]) {
; CHECK-NEXT:    [[W:%.*]] = load <3 x double>, ptr [[P]], align 32
; CHECK-NEXT:    store <3 x double> [[W]], ptr [[Q]], align 8
; CHECK-NEXT:    ret void
;
  %v = load <4 x double>, ptr %p, align 32
  %w = load <3 x double>, ptr %p, align 32
  call void @llvm.masked.store.v4f64.p0(<4 x double> %v, ptr align 8 %q, <4 x i1> <i1 true, i1 true, i1 true, i1 false>)
  store <3 x double> %w, ptr %q, align 8
  ret void
}

; Negative: the enabled lanes do not form a prefix. Lanes 0 and 2 cover
; tile[0, 8) and tile[16, 24), which no single address-and-size can describe,
; so the store keeps the upper bound of its vector type and is conservatively
; kept even though it does not really overlap the read.
define <4 x double> @hole_in_mask_is_not_narrowed(ptr %p) {
; CHECK-LABEL: define <4 x double> @hole_in_mask_is_not_narrowed(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    [[TILE:%.*]] = alloca [16 x double], align 32
; CHECK-NEXT:    [[ROW1:%.*]] = getelementptr inbounds nuw i8, ptr [[TILE]], i64 24
; CHECK-NEXT:    [[V:%.*]] = load <4 x double>, ptr [[P]], align 32
; CHECK-NEXT:    call void @llvm.masked.store.v4f64.p0(<4 x double> [[V]], ptr align 8 [[TILE]], <4 x i1> <i1 true, i1 false, i1 true, i1 false>)
; CHECK-NEXT:    call void @llvm.masked.store.v4f64.p0(<4 x double> [[V]], ptr align 8 [[ROW1]], <4 x i1> <i1 true, i1 true, i1 true, i1 false>)
; CHECK-NEXT:    [[R:%.*]] = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 8 [[ROW1]], <4 x i1> <i1 true, i1 true, i1 true, i1 false>, <4 x double> poison)
; CHECK-NEXT:    ret <4 x double> [[R]]
;
  %tile = alloca [16 x double], align 32
  %row1 = getelementptr inbounds nuw i8, ptr %tile, i64 24
  %v = load <4 x double>, ptr %p, align 32
  call void @llvm.masked.store.v4f64.p0(<4 x double> %v, ptr align 8 %tile, <4 x i1> <i1 true, i1 false, i1 true, i1 false>)
  call void @llvm.masked.store.v4f64.p0(<4 x double> %v, ptr align 8 %row1, <4 x i1> <i1 true, i1 true, i1 true, i1 false>)
  %r = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 8 %row1, <4 x i1> <i1 true, i1 true, i1 true, i1 false>, <4 x double> poison)
  ret <4 x double> %r
}

; Negative: an undef lane may or may not be written, so the prefix length is
; not known and the vector type is kept.
define <4 x double> @undef_lane_is_not_narrowed(ptr %p) {
; CHECK-LABEL: define <4 x double> @undef_lane_is_not_narrowed(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    [[TILE:%.*]] = alloca [16 x double], align 32
; CHECK-NEXT:    [[ROW1:%.*]] = getelementptr inbounds nuw i8, ptr [[TILE]], i64 24
; CHECK-NEXT:    [[V:%.*]] = load <4 x double>, ptr [[P]], align 32
; CHECK-NEXT:    call void @llvm.masked.store.v4f64.p0(<4 x double> [[V]], ptr align 8 [[TILE]], <4 x i1> <i1 true, i1 true, i1 undef, i1 false>)
; CHECK-NEXT:    call void @llvm.masked.store.v4f64.p0(<4 x double> [[V]], ptr align 8 [[ROW1]], <4 x i1> <i1 true, i1 true, i1 true, i1 false>)
; CHECK-NEXT:    [[R:%.*]] = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 8 [[ROW1]], <4 x i1> <i1 true, i1 true, i1 true, i1 false>, <4 x double> poison)
; CHECK-NEXT:    ret <4 x double> [[R]]
;
  %tile = alloca [16 x double], align 32
  %row1 = getelementptr inbounds nuw i8, ptr %tile, i64 24
  %v = load <4 x double>, ptr %p, align 32
  call void @llvm.masked.store.v4f64.p0(<4 x double> %v, ptr align 8 %tile, <4 x i1> <i1 true, i1 true, i1 undef, i1 false>)
  call void @llvm.masked.store.v4f64.p0(<4 x double> %v, ptr align 8 %row1, <4 x i1> <i1 true, i1 true, i1 true, i1 false>)
  %r = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 8 %row1, <4 x i1> <i1 true, i1 true, i1 true, i1 false>, <4 x double> poison)
  ret <4 x double> %r
}

; Negative: an all-enabled mask describes the whole vector, so there is nothing
; to narrow and the store still overlaps the read.
define <4 x double> @full_mask_is_not_narrowed(ptr %p) {
; CHECK-LABEL: define <4 x double> @full_mask_is_not_narrowed(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    [[TILE:%.*]] = alloca [16 x double], align 32
; CHECK-NEXT:    [[ROW1:%.*]] = getelementptr inbounds nuw i8, ptr [[TILE]], i64 24
; CHECK-NEXT:    [[V:%.*]] = load <4 x double>, ptr [[P]], align 32
; CHECK-NEXT:    call void @llvm.masked.store.v4f64.p0(<4 x double> [[V]], ptr align 8 [[TILE]], <4 x i1> splat (i1 true))
; CHECK-NEXT:    call void @llvm.masked.store.v4f64.p0(<4 x double> [[V]], ptr align 8 [[ROW1]], <4 x i1> <i1 true, i1 true, i1 true, i1 false>)
; CHECK-NEXT:    [[R:%.*]] = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 8 [[ROW1]], <4 x i1> <i1 true, i1 true, i1 true, i1 false>, <4 x double> poison)
; CHECK-NEXT:    ret <4 x double> [[R]]
;
  %tile = alloca [16 x double], align 32
  %row1 = getelementptr inbounds nuw i8, ptr %tile, i64 24
  %v = load <4 x double>, ptr %p, align 32
  call void @llvm.masked.store.v4f64.p0(<4 x double> %v, ptr align 8 %tile, <4 x i1> splat (i1 true))
  call void @llvm.masked.store.v4f64.p0(<4 x double> %v, ptr align 8 %row1, <4 x i1> <i1 true, i1 true, i1 true, i1 false>)
  %r = call <4 x double> @llvm.masked.load.v4f64.p0(ptr align 8 %row1, <4 x i1> <i1 true, i1 true, i1 true, i1 false>, <4 x double> poison)
  ret <4 x double> %r
}
